name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: .testcoverage.yml