name: ESLint check

on: 
  pull_request: 
    types: [opened, synchronize] 

jobs:
  check-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: echo "Running lint checks..."
      - name: Setup Node.js
        uses: actions/setup-node@v2 
        with: 
          node-version: '21.6.2' 

      - name: Restore cached dependencies 
        id: cache-restore 
        uses: actions/cache@v3 
        with: 
          path: ./frontend/node_modules 
          key: npm-${{ hashFiles('./package-lock.json') }} 
      - name: Install dependencies, then run lint
        if: steps.cache-restore.outputs.cache-hit != 'true' 
        working-directory: ./frontend
        run: | 
          npm ci - ignore-scripts 
          npm run lint